version: '3.8'

services:
  db:
    image: postgres:16
    environment:
      - POSTGRES_USER=paolo
      - POSTGRES_PASSWORD=supersecret
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432

  nest:
    build: .
    ports:
      - 3000:3000
    environment:
      - DATABASE_URL=postgresql://paolo:supersecret@db:5432/postgres
    depends_on:
      - db
    